Point to subctl repo for devel binaries download
submariner-io/get.submariner.io pull request #27
Opened 2022-05-11 13:59 UTC by Jaanki

Related to #21

Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

2022-05-11 14:13 UTC, skitt commented
The version-handling check for devel needs to be updated.

2022-05-11 15:18 UTC, tpantelis requested changes

2022-05-11 15:18 UTC, tpantelis commented on index.html
> +    release*|feature*)
@skitt and I were actually just discussing this. `devel` can retrieve from `subctl` as you've done here. `release*` and `feature*` need to as well but going forward - prior versions need to remain retrieving from `submariner-operator`. So:

```
feature-multi-active-gw|release-0.10|release-0.11|release-0.12)
    echo "https://github.com/submariner-io/submariner-operator/releases/download/subctl-${VERSION}/subctl-${VERSION}-${os}-${architecture}.tar.xz"
     return
     ;;
devel|release*|feature*)
    echo "https://github.com/submariner-io/subctl/releases/download/subctl-${VERSION}/subctl-${VERSION}-${os}-${architecture}.tar.xz"
     return
     ;;

```

2022-05-11 15:40 UTC, tpantelis commented
This [job](https://github.com/submariner-io/get.submariner.io/runs/6389436940?check_suite_focus=true) fails b/c this check:

`[[ "$(~/.local/bin/subctl version)" =~ ^"subctl version: subctl-devel"(-[0-9]+-g[a-f0-9]+)?$ ]]`

is incorrect - it's been failing for quite a while. It seems we used to name the version "_subctl-devel_" but it's now just "_devel_". Please make this change as well.

2022-05-11 16:02 UTC, tpantelis requested changes

2022-05-11 16:02 UTC, tpantelis commented on index.html
> +    feature-multi-active-gw|release-0.10|release-0.11|release-0.12)
This needs to be above L72 otherwise, eg, `release-0.12` will match L72 and fail.

2022-05-11 16:09 UTC, tpantelis commented
The [job](https://github.com/submariner-io/get.submariner.io/runs/6391421364?check_suite_focus=true) for `release-0.8` also failed. Perhaps we should change it to check for `release-0.12` but, either way, should we handle `release-0.8` (@skitt )? I guess it wouldn't hurt to include `release-0.8` to `release-0.12`.

2022-05-11 16:12 UTC, Jaanki commented
> The [job](https://github.com/submariner-io/get.submariner.io/runs/6391421364?check_suite_focus=true) for `release-0.8` also failed. Perhaps we should change it to check for `release-0.12` but, either way, should we handle `release-0.8` (@skitt )? I guess it wouldn't hurt to include `release-0.8` to `release-0.12`.

I was thinking the same. From 8-12, get from operator repo and after that from subctl repo.

2022-05-11 16:29 UTC, skitt requested changes

2022-05-11 16:29 UTC, skitt commented on index.html
> +    feature-multi-active-gw|release-0.10|release-0.11|release-0.12)
```suggestion
    feature-multi-active-gw|release-0.?|release-0.1[012])
```

2022-05-11 16:38 UTC, tpantelis commented on index.html
> +    feature-multi-active-gw|release-0.10|release-0.11|release-0.12)
We can keep the `release-0.8` test job and add one for `release-0.12`. Once the `release-0.13` branch is created we can add a test for that.

2022-05-12 05:11 UTC, tpantelis approved these changes

2022-05-12 18:59 UTC, dfarrell07 approved these changes

2022-05-13 10:38 UTC, skitt approved these changes

2022-05-13 10:41 UTC, merged