Update the binary path
submariner-io/get.submariner.io pull request #51
Opened 2023-07-17 10:26 UTC by Jaanki

in accordance with https://github.com/submariner-io/subctl/pull/837 changing the `subctl` binary location.

Epic: https://github.com/submariner-io/enhancements/issues/182

2023-07-17 14:59 UTC, skitt requested changes

2023-07-17 14:59 UTC, skitt commented on index.html
> +      install_subctl subctl*/subctl
Since get.submariner.io can install older releases, this needs to handle both naming schemes.

2023-07-18 13:08 UTC, Jaanki commented
devel check will pass only after merging https://github.com/submariner-io/subctl/pull/837

2023-07-18 15:04 UTC, skitt requested changes

2023-07-18 15:04 UTC, skitt commented on index.html
> +      fi
Given that each tarball ships a single binary, I think we can get away with

```suggestion
      install_subctl subctl*/subctl*
```

This avoids having to deal with 0.16.0 pre-releases too ;-).

2023-07-19 07:24 UTC, skitt approved these changes

2023-07-19 08:03 UTC, sridhargaddam approved these changes

2023-07-19 08:04 UTC, merged