Add some embedded HTML for get.submariner.io
submariner-io/get.submariner.io pull request #6
Opened 2020-09-25 13:21 UTC by mangelajo

This adds some HTML in the script, so in case someone
visits get.submariner.io from a browser something
meaningful will be displayed.

It's not perfect, and still it's not valid HTML because
of the initial bash header, but, it's ok for browsers

Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>

2020-09-25 13:23 UTC, dfarrell07 approved these changes

2020-09-25 13:29 UTC, skitt requested changes, later dismissed

2020-09-25 13:29 UTC, skitt commented on index.html
> +#--> </ul> <!--
```suggestion
#--> <p>I'm served from GitHub pages and my source code lives here: <!--
#-->   <a href="https://github.com/submariner-io/get.submariner.io">get.submariner.io @ github.com</a></p> <!--
#--> <p>You can find some useful links here: <!--
#--> <ul><li> <a href="https://submariner.io/quickstart/kind/#install-subctl">A quickstart on installing submariner</a> </li> <!--
#-->     <li> <a href="https://submariner.io/">The Submariner website</a> </li><!--
#-->     <li> <a href="https://submariner.io/contributing/">References to our slack channel and contribution guidelines</a> </li><!--
#--> </ul></p> <!--
```

2020-09-28 07:55 UTC, skitt approved these changes

2020-09-28 07:56 UTC, merged